#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Fix Sidebar CSS Visibility
# Spec: 001-fix-sidebar-css-visibility

set -e

echo "========================================"
echo "CurryDash Docs - Development Environment"
echo "Fix Sidebar CSS Visibility"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."
cd docs

if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing npm packages...${NC}"
    npm install
else
    echo -e "${GREEN}Dependencies already installed${NC}"
fi

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo -e "${YELLOW}Starting Next.js dev server...${NC}"
npm run dev &

# Wait for dev server
wait_for_service 3000 "Next.js Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Documentation: http://localhost:3000"
echo ""
echo "Next Steps:"
echo "  1. Open http://localhost:3000 in your browser"
echo "  2. Check if sidebar is visible on the left"
echo "  3. Test responsive behavior with browser DevTools"
echo ""
echo "To stop the dev server, press Ctrl+C"
echo ""
